[tools]
kubectl = "latest"
helmfile = "latest"
helm = "latest"
yamllint = "latest"
"cargo:deadnix" = "latest"
hk = "latest"
pkl = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"
