---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  labels:
    app: prometheus
    name: prometheus-datasource
    grafana_datasource: "true"
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus Server
        type: prometheus
        url: http://prometheus-server.prometheus:80
        isDefault: true
        isEditable: true
