apiVersion: ENC[AES256_GCM,data:Iwg=,iv:XEZsxifc3gIHEt4d+JO4cMzzrl+X/zTZPoD9LG/qnXc=,tag:TeI/LHDsCPKYCcQ613DPuA==,type:str]
kind: ENC[AES256_GCM,data:CWEO/yIq,iv:U/7bReXZ9V4+n/x6LJIrSxUyMbF2ntJAD+DiqUJhbf0=,tag:ynbNviFy8le4snGE7SKFbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Tnb7OEb6+wt1Hj5Hqgff3xoIdA==,iv:f3/yFQiLG+S3PAsxeEKvIdRwE2UhpnX55QcW7qkpiP8=,tag:6y3hGIrt9Cr0nxBk5rplQw==,type:str]
    namespace: ENC[AES256_GCM,data:kN71o+5xOg==,iv:30oQyU7TUuEFdRxXH++DcPMW4c+3fmpMy8EQ6iH//dk=,tag:uUq7Zv77HIANaFlzaLcgxA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:vSzgE2kGQg==,iv:XdnSUEZAJWOkgQJiL35VnWmXNcaLAth+DUV2t9Axxb8=,tag:Eekd8WknfU01ZbRhAk5FBw==,type:str]
stringData:
    GF_AUTH_GENERIC_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Ig2uIaswhE0MbMCwPFhYE0p13mZdWg==,iv:HX69zsChpO1BZDQ4jvQTHdZTuJ0261CD9gAa1Ar3OtM=,tag:NcqamSJ5Nau4tHls0lzsVQ==,type:str]
#ENC[AES256_GCM,data:C6E6kbx4pP7bkoawR0r9A83HnOmGJJz4WIxPnpygzm8BPMMy7cHi/vMplw/eMOyaSdrS6YeoMThYGkJtizVY6F7TiRhTXlzHRyimCvqn9BMMw8ZQ6IyC,iv:Dj1rzAF93c0FfGOq5evyhSZbhU2GOGzzejN/3zwEgh8=,tag:8rkfIRTlQWXN6UoDGbvjGw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWlFUQkdVUmsycUN2NWMr
            UWFHZDNZT05oRW93OWxHZ3RKMDlNa2IvS0dFClFORTRsTFRNZW9kQ1k4UTgzL1RE
            eWNQM0VkZDlvL004NTZ4elF3RkxqSGcKLS0tIEtQeWFZRHlTMmJzNkN1amhqSVRX
            RVFWNVdLanB3U3VSOFBqMWtobWsraGsKGj/PeTg47RX1pYUuqav7lBkbXuotKvZm
            ibT/ZebpL5nx6cZ1mO5k9CYWD6s5l0vqodLeGreovdguCcqbLtF8yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T21:09:35Z"
    mac: ENC[AES256_GCM,data:aLhH62QZfrEFH+gj/icnFVKirnSDWm9pIopVHm2smysbXs+qfoh5SbpiPkxPFyKP67Mo7QxjwvpwV5s+3U4pJa9nE+NNklE04NNpP7JTu6rvLeUCE7TtjoXBvNevxdBymcJioGp2ZP1LDCJ+9xkb7KW5NfFll9F/+2EQ2hVP8hU=,iv:FW76g19NlthkaQrb11mF5TZX4trsSFZEYgrvP3eGkCg=,tag:Fm1u6SMXZkco70xSLE1uqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
