apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: openclaw
    labels:
        app: openclaw
stringData:
    gateway-token: ENC[AES256_GCM,data:v1Cs1g9O0DLq58HB/73K66a/7GhgTa8WP2bODTHYDo8m5b7sdAZFd8rujNqRUep64nR7SYabpPb3JJs5aBjJsg==,iv:STYTjBRizXcMAmZuHURHb6i7sHXz1+rAWLK/x5l24IU=,tag:skJjY9c7E3UnzScNMTf/Tw==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:Z7scgwXCZ8XK0qgeIRSbXoGZ7sA3yzX7z8Q64mr57y4eIk8=,iv:cqzNqsQC4X8h5yVXYc/E+iMgQdjZG6kNmWFxTk2BZmQ=,tag:i2To49XoDN5H5WhQ3poTYQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:qXhtIi/jpjLd16tyeqHVG/Q5rgDaFI9kk50GZyt6W8RjpjNs5ZX+jKBDRx6gYg==,iv:2gbJ/OPjjCRi+eGo2l690aV0Vy6apRDCTyBM33LqHKE=,tag:D3EmlYM7GMSOT7ifznwyew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRWpYSmFTeDVPY05UWEhw
            S1o2UU40c0FIaTViNWRGRnJ1TDJVeURmZEI0CjlIZVh5U0RtL2xON081RStTb3VQ
            bHVqSmY0UVNZeVNidThkTnJ2RmcvMHMKLS0tIExSaVhQdFRKRXhRUkpDdDVsbHB3
            Y0FiSk1wTFJTMWdNZHFRTmhjL01qWE0KVwFHO2hEuFRLKBPTQJpI6DKHN7EPb/1d
            l4//re02vFt6cTsFoCuD2TpMJV6wgl4JHoVxZr97TxmFlgnb7HHQHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T21:42:01Z"
    mac: ENC[AES256_GCM,data:PJu5kqfOoMBsJC9O5rYuH3d8ZTAiJarQsL6v9q5wwyZnDRh8pdxXXeuRyjyf+CZCDYmb/8jE8AvniMAdabSldyiKv7ZPJAVLi1cPYdWk2GNQXBuv/vV+46uncbCH7jd0R42ApTtmL2vzVJzlsVmSGa8vjSVSZIb5XS2GTw/H48w=,iv:lerqYmyDfw18XyR3rBKFrqhphbYBeghEwjY2yrnOG8Q=,tag:9q6Z7gyZ4JtBQCnUi45GAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
