---
repositories:
  - name: gitlab
    url: https://charts.gitlab.io
---
releases:
  - name: gitlab
    namespace: gitlab
    chart: gitlab/gitlab
    version: ~8.11.0
    values:
      - ./values.yml
