apiVersion: v1
kind: Secret
metadata:
    name: authentik-auth
    namespace: authentik
    labels:
        app: authentik
stringData:
    postgres-password: ENC[AES256_GCM,data:fwuU1BVR99oi2Gt6r/ss7A==,iv:ynt1roK5JpjtfewWlZ5fOCmi202IB5amdNWjjN11yag=,tag:o03Eoyxv43W5pJJD/44zSg==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:SezJN05+1TA=,iv:1R4pMVPN76YsSodRjRv9SK+p2m0YV+bbxrG48OURwOg=,tag:skfVoC2oYRUvuu0BF2Pcjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eXJyQURjZStwWkNtakdj
            UXNiZFM5OTZzYytSWlFOU3ZrdXB1azZ3MlR3CkR3MGl6cjhCQmFQcWg3SUFydDVh
            WjRVWkdqQXJ6allYMHpQMnF2aGVaa0EKLS0tIE1sMUdKTStUMEZXMFlGM3BTVUVp
            SU4zN05FOEg3Q1pZSjkybWdmUEl4UlkK3VzfqaVxxmz/pnx8r13M/pCOz0L7GRLm
            HTVimQs79b5oGkmOWW/10/gw2YsJ/xgbGOXyF6c8h9vQve7n8X63cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T21:54:43Z"
    mac: ENC[AES256_GCM,data:LCLZNF0N/vJP4sM+UHspBPrVz9c7RukS8zYAfWuXYkgqazKjlRov3dZ7IulRoOsshXIZWU0SrUPp3u1hYRq6I5Ux+FX0kzijZTfsFz9+KxAHGVNvZh/Ykma7TRxl1UAamFz+iofHXOTKzvSVIC/ccwuclXTLreuwxW+x4BptRzE=,iv:+pWjhXsJjG3JJj1rKLImZ4W8eu21XnVJtl3yZJZfOYA=,tag:4dDQKSrymtfc7Rd1AgWmqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
