apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-auth
    namespace: authentik
    labels:
        app: authentik
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:fA1Jdrgrl/JU,iv:a+S/hsJFSeuZAZKEMI7n6/6mxA1OCZtwSCztDV4sY9E=,tag:1Cmd8YbYMW7z9l8HxvjWSw==,type:str]
    password: ENC[AES256_GCM,data:zEscih77XkliQJrqmlHHLckN,iv:/mo5aE01X+2u2ib3HzsqZrOOPTo9AaJoBLwNJ+D+wCc=,tag:qsvipoqI0+5/aVdaofkpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcmk5TGUzWXJ0U0JpMnhN
            NVkyc3FucnMzakNNbFp4R281NmhaY05LaFFvCjZaRTdqRnlCcEpvdlpMcWt0RTFM
            S1V2MVh0TmRNQkJGdWpJY0taY2MyYW8KLS0tIEVGaU5XemdUVnFkZXpMUmd6b2Zt
            MWlJNnhTUkwrd0NUcTRkN2RzMUVCNTgKhYkLLciAmZrA4air2l4aLfcbA3dwg7G2
            DfgSUWsW8dc+p4zSppyw82UdSpoT6yfCZgQ/L2EB7Moexgbj6UPTKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T15:08:16Z"
    mac: ENC[AES256_GCM,data:/I2pGqOyYigjR+AhqVWlq5K+cObbVr4rDmAwp/M+viilgxxjlDrM2oG3ix2lGgueanjXvJDkutGJHKSr70zVjlwiTtQv6d+RS8Z/lAWFFNW6aU4Mo8b+Q9zfV1tQwNQQl4UpYEp5lUu8Dy6bykIfnb/qVxGhuQEUNUKP1BNX0Cg=,iv:9ZmxHZKFXlqXJS1MFrZRXjis+h2yyX6AE4NZek7NhNE=,tag:y0nVFw7vHkmrYT5+op2MLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
