apiVersion: ENC[AES256_GCM,data:DdY=,iv:Ll3eTszlIk8Q6/tDOt82MqklyEEAAMcnijwapKeuT5g=,tag:gcwfH8/dwKgNZ8UsfMeuXA==,type:str]
kind: ENC[AES256_GCM,data:O/fWa5sp,iv:qRaXyDgNAcNmD6qHM5FkVKe5tFUeqXg6KbqwkNh96I8=,tag:VQy/mMQXaTupjivNe+cMaw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AQkXS7uehKjkuOR+ktIhztxuabosXjQ=,iv:H2rLQjqTPgv5ZFy3Qmfy53Sw193DVcfWB97locFSjvA=,tag:Nk7XHWxXFm5l9sWf2LgyEw==,type:str]
    namespace: ENC[AES256_GCM,data:ZWKakLTzV/ks,iv:QWdxTSLwQlKJSt9IA82hInqZU5BNX6mnAQpJUWmhpXk=,tag:7wtgZPMU2j+zySGbI/ZFHA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:hEi2REoJI73c,iv:YaB3/CjdVrBLfkG8h32lH0/dSIAbSsGj25C0ia+bSE4=,tag:pqC8dgO5cY+9rq+S+nNDKA==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:ymy1I0fQIBuRKyFfNGnAkQ==,iv:YQrD8c6ZJ3bEjmgzW1np7PQS+nZGF+ol7IE+NK1L3DQ=,tag:9bQi57Rtb6zD2HgC3DDbwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZHdvV1FRcnVYTzM2amJT
            eHBENGd5MjZCZEhPTFRkeTJDVHVvTDBXK2hBCndCaW1GMmtxS01jZmtXZTFDOVBk
            VnFaZEp0YUR6K0ljYnRVWnJYNHNVSFkKLS0tIGVyalJuQmdvVjlRZzFVWXdyWXVz
            M3ZSaFFha1FrOTFiL0hnOExjaFRrYUkKhtCZdysPYO0a76zA+si/3TGy30efI13W
            dLxOXl3OzdzbCXGJnDFH4FRCajZDfmixGeSdHWopYY4w5wEmBeelEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T21:09:33Z"
    mac: ENC[AES256_GCM,data:rahWb2ykDohBnr/PbnveAbL9KPDURYGeMOB/5BVUI3UvroKGAd/5CxvofV2G3nz5KRburqT9oxc56QLYRZZX/3+LmLrUf2PVioHy2rN9c366oTKQNT4kHpuxZMwj0CjpJWWwysG5+L2LvKD54rYoih/n6uaPae2oyA9jcY/WUwg=,iv:OUOTeXTIc5YeLjgjdqaoYr1olWWua005rYaku6A20vI=,tag:wa1RxpfvdUm1YWd5ruHLHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
