apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
    labels:
        app: authentik
stringData:
    secretkey: ENC[AES256_GCM,data:GfJJtCX6ldoJYFlrSTqiWwcQPHHytuHnbc8p8n7bnKc=,iv:uorXandcBQ+2vcB4OSI5M4s2TG89/2THRJEAb9uOSvc=,tag:t/N0KgkxgEcFoeCiExGmbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVXhmWlBhWVVUM0MzSTMy
            aTBMbXJMZTdpWTBOZXF2YzVBK3V2cWlEMlRRCmtRajBKanhiTlV2eFdTSXNoaCtF
            WSthRTRUZ1E0NFFmWi9lRXBIeUZZLzgKLS0tIGlJTmFiamZkdnJUMVhxYjJRcUxk
            RkpUbUNsUXpQM1JPdmJBdEdKbkdtUUkKLJ45U8BljvLCdBtz1G/CQ4v9lwfpo6U4
            Tn9fZB3v5j3ppYxqmZsqsXkPmDAUueEDGPqTCDraVfGdInZca3UyKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T15:08:20Z"
    mac: ENC[AES256_GCM,data:Y3ITUDJbTzrsrepsR0z4T0MJ6AtdNmWiKtFAWDSQA1bhh06EcnPmGb4K9ARwkAaUnYPG5BGsbDsIhN6/fJe7mgjsleEoQer7cRuYMXPLnUXiBJxqQ53pDcLHdHMGWMCD4p0kUnu0VyC1c8Y+zZeWcYUe3nG1hvPrdc8Ci5P2bZU=,iv:w7oJsLSEmFUO8JzR3Ai7EMGxD4ZnAHrM2JgcSJuRwGE=,tag:qVGN3jnaHMO1/D5T6q1lpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
