#!/usr/bin/env bash
#MISE description="Helmfile diff for a layer"
#USAGE arg "<layer>" help="Target layer: core, platform, or apps" {
#USAGE   choices "core" "platform" "apps"
#USAGE }
helmfile -f "kubernetes/${usage_layer?}" diff
