---
global:
  domain: argo.homelab.local
  addPrometheusAnnotations: true

configs:
  params:
    # tls already handled by ingress
    server.insecure: true

  cm:
    url: https://argo.homelab.local
    oidc.config: |
      name: Authentik
      issuer: https://identity.homelab.local/application/o/argocd/
      clientID: argocd
      clientSecret: changeme
      requestedScopes: ["openid", "profile", "email", "groups"]
      insecureSkipVerify: true

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, ArgoCD Admins, role:admin

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argo.homelab.local
    annotations:
      cert-manager.io/cluster-issuer: certificate-issuer
    tls:
      - secretName: argocd-homelab-local-tls
        hosts:
          - argo.homelab.local
