---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-custom
  namespace: argocd
  labels:
    app: argocd
spec:
  generators:
  - scmProvider:
      gitea:
        owner: homelab
        api: https://git.homelab.local/
        insecure: true
  template:
    metadata:
      name: '{{repository}}-application'
      namespace: argocd
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      project: default
      source:
        repoURL: http://gitea-http.gitea:3000/homelab/{{repository}}
        targetRevision: HEAD
        path: manifests
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{repository}}'
