---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: homelab-0
  namespace: longhorn-system
spec:
  disks:
    nvme:
      path: /var/lib/longhorn
      allowScheduling: true
      storageReserved: 0%
    sd:
      path: /sd
      allowScheduling: true
      storageReserved: 0%
