---
repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
---
releases:
  # k9s is good but not enough
  - name: dashboard
    namespace: dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.10
    values:
      - ./values/dashboard.yml

  # internal DNS + no more ads
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.27.0
    values:
      - ./values/pihole.yml

  # needed for LoadBalancer svcs on bare-metal k8s
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.8

  # Auto-sync ingresses with local DNS provider
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
      - ./values/dns.yml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.11.3
    values:
      - ./values/ingress-controller.yml
