---
DNS1:
  192.168.1.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - "dns.homelab.local"
serviceDns:
  loadBalancerIP: 192.168.1.64
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
