---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
---
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: ~1.20.0
    values:
      - ./values.yml

  - name: trust-manager
    namespace: cert-manager
    chart: jetstack/trust-manager
    version: ~0.24.0
    needs:
      - cert-manager
