---
DNS1:
  192.168.1.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "dns.homelab"
serviceWeb:
  loadBalancerIP: 192.168.1.64
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.1.64
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
