---
redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  accessModes:
    - ReadWriteMany

actions:
  enabled: true
  statefulset:
    extraVolumes:
      - name: custom-ca-bundle
        configMap: 
          name: custom-ca-bundle
    dind:
      tag: dind
      extraVolumeMounts:
        - name: custom-ca-bundle
          mountPath: /etc/docker/certs.d/registry.homelab.local
          readOnly: true
    actRunner:
      extraVolumeMounts:
        - name: custom-ca-bundle
          mountPath: /etc/docker/certs.d/registry.homelab.local
          readOnly: true
      config: |
        container:
          privileged: true
          network: "host"
          options: "-v /certs:/certs --env DOCKER_TLS_VERIFY=1 --env DOCKER_CERT_PATH=/certs/server --env DOCKER_HOST=tcp://127.0.0.1:2376"
          valid_volumes:
            - '**'
        runner:
          labels:
            - "ubuntu-latest:docker://sverdejot/act:latest"

  provisioning:
    enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
  className: nginx
  hosts:
    - host: git.homelab.local
      paths:
        - path: /
          pathType: Prefix

service:
  ssh:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.67
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/allow-shared-ip: gitea
