---
redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true

actions:
  enabled: true
  provisioning:
    enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
  className: nginx
  hosts:
    - host: git.homelab.local
      paths:
        - path: /
          pathType: Prefix

service:
  ssh:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.67
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/allow-shared-ip: gitea
