---
apiVersion: v1
metadata:
  name: counter
  labels:
    app: counter
    name: counter
kind: Namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: counter
  labels:
    name: counter-deployment
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: counter
          image: registry.homelab.local/sverdejot/counter:v0.1.0
          ports:
            - containerPort: 8080
      imagePullSecrets: 
      - name: auth
---
apiVersion: v1
kind: Service
metadata:
  name: counter-svc
  namespace: counter
  labels:
    name: counter-svc
    app: counter
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: counter
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-ingress
  namespace: counter
  labels:
    app: counter
    name: counter-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: counter.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: counter-svc
                port:
                  number: 80



